version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"  
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql

  app:
    depends_on:
      - db
    image: dilysnguyen/sgroup_be:20.9.1
    environment:
      PORT: ${PORT}
      LOCAL_HOST: host.docker.internal
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
