name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Cache Docker Image Layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: dilysnguyen/sgroup_be:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@3.106.182.153 << 'EOF'
            # Dừng và xóa các container cũ nếu cần
            docker stop polling-app-server-app-1 || true
            docker rm polling-app-server-app-1 || true
        
            
            # Kéo hình ảnh Docker mới từ Docker Hub
            docker pull dilysnguyen/sgroup_be:latest

            # Chạy container MySQL mới
            # docker run -d --name my_mysql_db \
            #   --network my_network \
            #   -e MYSQL_ROOT_PASSWORD=231203 \
            #   -e MYSQL_DATABASE=sgroup_be \
            #   -p 3306:3306 \
            #   mysql:5.7

            # Chạy container ứng dụng
            docker run -d --name polling-app-server-app-1 \
              --network my_network \
              -e PORT=3000 \
              -e DB_USER=root \
              -e DB_PASS=231203 \
              -e DB_NAME=sgroup_be \
              -e DB_HOST=my_mysql_db \
              -p 3000:3000 \
              dilysnguyen/sgroup_be:latest
          EOF
